### ISSUE TITLE
[Feature]: Tree

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/binary-tree-zig#1]
### Description

Implement a generic Tree struct.

### Todo

- [x] Create a generic function returning the `Tree` type.
- [x] Add a type guard to make sure the key is always a number type.
- [x] Implement a method for adding a new `Node` to the `Tree`.
- [ ] Implement a method for deleting a `Node` from the `Tree`.
- [ ] Implement a method for checking if the `Tree` contains a node.
- [ ] Implement a method to convert the `Tree` to a sorted array.

### Definition Of Done

- [ ] Did you create a new branch?
- [ ]  Did you commit after each major change?
- [ ] Did you complete all steps outlined in this issue?
- [ ]  Did you make a pull request to merge with the dev branch?
