### ISSUE TITLE
[Feature]: Value field

### ISSUE THREAD

**Issue by VantorreWannes** [VantorreWannes/binary-tree-zig#2]
### Description

Add a node value field.

### Todo

- [ ] Rename the `value` field to `key` for clarity.
- [ ] Adjust the generic `Node` struct to contain a new field containing the data associated with its `key` field.

### Definition Of Done

- [ ] Did you create a new branch?
- [ ]  Did you commit after each major change?
- [ ] Did you complete all steps outlined in this issue?
- [ ]  Did you make a pull request to merge with the dev branch?
